# Don't edit the `bin` list manually. Run `rustlings dev update` after changing
# exercises or solutions.
bin = [
  { name = "lesson0", path = "exercises/00_intro/lesson0.rs" },
  { name = "lesson0_sol", path = "solutions/00_intro/lesson0.rs" },
  { name = "lesson1", path = "exercises/01_packing/lesson1.rs" },
  { name = "lesson1_sol", path = "solutions/01_packing/lesson1.rs" },
  { name = "lesson2", path = "exercises/01_packing/lesson2.rs" },
  { name = "lesson2_sol", path = "solutions/01_packing/lesson2.rs" },
]

[package]
name = "ratlings"
version = "0.1.0"
description = "Small and interactive exercises for learning Ratatui"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
ratatui = "0.30.2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
