# Don't edit the `bin` list manually. Run `rustlings dev update` after changing
# exercises or solutions.
bin = [
  { name = "pack1", path = "exercises/01_packing/pack1.rs" },
  { name = "pack1_sol", path = "solutions/01_packing/pack1.rs" },
  { name = "pack2", path = "exercises/01_packing/pack2.rs" },
  { name = "pack2_sol", path = "solutions/01_packing/pack2.rs" },
]

[package]
name = "ratlings"
version = "0.1.0"
description = "Small and interactive exercises for learning Ratatui"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
ratatui = "0.30.2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
